// File autogenerated with yaml2cpp.rb

#ifndef STATEMACHINE_EXAMPLESTATEMACHINE_H_
#define STATEMACHINE_EXAMPLESTATEMACHINE_H_

#include "core/StateMachine.h"

class ExampleStateMachine : public vd::core::StateMachine<ExampleStateMachine> {
public:
	ExampleStateMachine();

protected:
virtual void CommonUpdate(const float time_ms);

private:
	void StateStart(const float time_ms);
	void StateCleanUp(const float time_ms);
	void StateInit(const float time_ms);
	void StateExit(const float time_ms);
};

#endif // STATEMACHINE_EXAMPLESTATEMACHINE_H_
