// File autogenerated with yaml2cpp.rb

#include "ExampleStateMachine.h"

ExampleStateMachine::ExampleStateMachine()
: Super(&ExampleStateMachine::StateInit)
{

}

void ExampleStateMachine::CommonUpdate(const float time_ms)
{

}

// ---------------------------------------------------------
// States
// ---------------------------------------------------------
#pragma mark States

void ExampleStateMachine::StateInit(const float time_ms)
{
	if (false /* everything ready */) {
		SwitchTo(&ExampleStateMachine::StateStart);
	}
}
void ExampleStateMachine::StateStart(const float time_ms)
{
	if (false /* close */) {
		SwitchTo(&ExampleStateMachine::StateExit);
	}
}
void ExampleStateMachine::StateExit(const float time_ms)
{
	SwitchTo(&ExampleStateMachine::StateCleanUp);
}
void ExampleStateMachine::StateCleanUp(const float time_ms)
{
}
